<template>
  <div>
    <card title="Job Order Allocations">
      <ServerTable :headers="headers" :url="`/api/job-orders/${jobOrderId}/allocations`">
        <template #item_voucher="{row, value}">
          <nuxt-link :to="`/allocations/${row.id}`">
            {{ value }}
          </nuxt-link>
        </template>
      </ServerTable>
    </card>
  </div>
</template>
<script>
import ServerTable from '~/components/Tables/ServerTable'

export default {
  components: { ServerTable },
  props: {
    jobOrderId: {
      type: Number,
      required: true
    }
  },
  data () {
    const headers = [
      {
        label: 'Partner',
        field: 'partner'
      },
      {
        label: 'Branch',
        field: 'branch'
      },
      {
        label: 'Plan',
        field: 'plan'
      },
      {
        label: 'Voucher',
        field: 'voucher'
      },
      {
        label: 'Allocation Type',
        field: 'allocation_type'
      },
      {
        label: 'Allocation',
        field: 'allocation_formatted'
      },
      {
        label: 'Price',
        field: 'price'
      },
      {
        label: 'Sold',
        field: 'is_sold',
        formatValue: value => value ? 'Yes' : 'No'
      },
      {
        label: 'Date Sold',
        field: 'date_sold'
      },
      {
        label: 'Generated by',
        field: 'generated_by'
      },
      {
        label: 'Date Created',
        field: 'created_at'
      }
    ]
    return {
      headers
    }
  }
}
</script>
