<template>
  <card title="Allocation Details">
    <h4>
      Basic
      <span v-show="isComplimentary" class="badge badge-info">Complimentary</span>
    </h4>
    <hr>
    <el-row :gutter="15" class="flex-wrap mb-3" type="flex">
      <el-col :lg="12" class="mb-2">
        <p>
          Voucher: <br>
          <strong>{{ allocation.voucher }}</strong>
        </p>
      </el-col>
      <el-col :lg="12" class="mb-2">
        <p>
          Price: <br>
          <span v-if="isFree" class="badge badge-success">FREE</span>
          <strong v-else>{{ allocation.price }}</strong>
        </p>
      </el-col>
      <el-col v-show="isComplimentary" :lg="12" class="mb-2">
        <p>
          Mobile Number: <br>
          <strong>{{ allocation.mobile_number }}</strong>
        </p>
      </el-col>
      <el-col v-show="!isComplimentary" :lg="12" class="mb-2">
        <p>
          Partner: <br>
          <strong>{{ allocation.partner }}</strong>
        </p>
      </el-col>
      <el-col v-show="!isComplimentary" :lg="12" class="mb-2">
        <p>
          Branch: <br>
          <strong>{{ allocation.branch }}</strong>
        </p>
      </el-col>
    </el-row>

    <h4>Allocations</h4>
    <br>
    <el-row :gutter="15" class="flex-wrap mb-3" type="flex">
      <el-col :lg="12" class="mb-2">
        <p>
          Plan: <br>
          <strong>{{ allocation.plan }}</strong>
        </p>
      </el-col>
      <el-col :lg="12" class="mb-2">
        <p>
          Allocation Type: <br>
          <strong>{{ allocation.allocation_type }}</strong>
        </p>
      </el-col>
      <el-col :lg="12" class="mb-2">
        <p>
          Allocation: <br>
          <strong>{{ allocation.allocation_formatted }}</strong>
        </p>
      </el-col>
      <el-col :lg="12" class="mb-2">
        <p>
          Rate Limit: <br>
          <strong>{{ allocation.rate_limit }}</strong>
        </p>
      </el-col>
      <el-col :lg="12" class="mb-2">
        <p>
          Sold: <br>
          <span v-if="allocation.is_sold" class="badge badge-success">Yes</span>
          <span v-else class="badge badge-light">No</span>
        </p>
      </el-col>
      <el-col :lg="12" class="mb-2">
        <p>
          Date Sold: <br>
          <strong>{{ allocation.date_sold ? defaultDateTimeFormat(allocation.date_sold) : '-' }}</strong>
        </p>
      </el-col>
      <el-col v-show="!isComplimentary" :lg="12" class="mb-2">
        <p>
          Generated By: <br>
          <strong>{{ allocation.generated_by }}</strong>
        </p>
      </el-col>
      <el-col :lg="12" class="mb-2">
        <p>
          Date Created: <br>
          <strong>{{ defaultDateTimeFormat(allocation.created_at) }}</strong>
        </p>
      </el-col>
    </el-row>
    <div v-show="!isComplimentary" class="others">
      <h4>Others</h4>
      <hr>
      <el-row :gutter="15" class="flex-wrap mb-3" type="flex">
        <el-col>
          <p>
            Job Order:
            <nuxt-link v-if="allocation.job_order_id" :to="`/job-orders/${allocation.job_order_id}`">
              View Job Order
            </nuxt-link>
            <span v-else>-</span>
          </p>
        </el-col>
      </el-row>
    </div>
  </card>
</template>
<script>
import { dateTimeFormat } from '~/util/utilities'

export default {
  name: 'AllocationDetails',
  props: {
    allocationId: {
      type: Number,
      required: true
    }
  },
  data () {
    return {
      allocation: {}
    }
  },
  async fetch () {
    this.allocation = await this.$store.dispatch('allocation/get', this.allocationId)
  },
  computed: {
    isComplimentary () {
      return this.allocation.mobile_number !== null
    },
    isFree () {
      if (this.allocation.price === null) { return false }

      return Number(String(this.allocation.price).replace(/[^\d]/, '')) === 0
    }
  },
  methods: {
    defaultDateTimeFormat (value) {
      return dateTimeFormat(value)
    }
  }
}
</script>
